<a href="https://colab.research.google.com/github/Kgs-Mathaba/ARIMA_and_Seasonal_ARIMA/blob/main/10_time_series_forecasting_with_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# time series forcasting with tensorflow
# predict the price of bitcion
# data collected from coindesk in csv format

In [2]:
# Download Bitcoin historical data from GitHub 
# Note: you'll need to select "Raw" to download the data in the correct format
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/BTC_USD_2013-10-01_2021-05-18-CoinDesk.csv

--2022-01-26 07:44:02--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/BTC_USD_2013-10-01_2021-05-18-CoinDesk.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 178509 (174K) [text/plain]
Saving to: ‘BTC_USD_2013-10-01_2021-05-18-CoinDesk.csv’

BTC_USD_2013-10-01_ 100%[===================>] 174.33K  --.-KB/s    in 0.02s

2022-01-26 07:44:02 (7.76 MB/s) - ‘BTC_USD_2013-10-01_2021-05-18-CoinDesk.csv’ saved [178509/178509]

In [3]:
import pandas as pd
df = pd.read_csv('/content/BTC_USD_2013-10-01_2021-05-18-CoinDesk.csv',
                 parse_dates=['Date'],
                 index_col=['Date'])
df.head(20)

           Currency  Closing Price (USD)  ...  24h High (USD)  24h Low (USD)
Date                                      ...
2013-10-01      BTC            123.65499  ...       124.75166      122.56349
2013-10-02      BTC            125.45500  ...       125.75850      123.63383
2013-10-03      BTC            108.58483  ...       125.66566       83.32833
2013-10-04      BTC            118.67466  ...       118.67500      107.05816
2013-10-05      BTC            121.33866  ...       121.93633      118.00566
2013-10-06      BTC            120.65533  ...       121.85216      120.55450
2013-10-07      BTC            121.79500  ...       121.99166      120.43199
2013-10-08      BTC            123.03300  ...       123.64016      121.35066
2013-10-09      BTC            124.04900  ...       124.78350      122.59266
2013-10-10      BTC            125.96116  ...       128.01683      123.81966
2013-10-11      BTC            125.27966  ...       126.43666      124.11383
2013-10-12      BTC            125.92750  ...       126.03650      123.12966
2013-10-13      BTC            126.38333  ...       126.89650      125.27650
2013-10-14      BTC            135.24199  ...       135.24199      126.25500
2013-10-15      BTC            133.20333  ...       135.69216      130.39275
2013-10-16      BTC            142.76333  ...       143.60483      132.94933
2013-10-17      BTC            137.92333  ...       145.60100      136.01466
2013-10-18      BTC            142.95166  ...       144.31100      137.53966
2013-10-19      BTC            152.55183  ...       152.66850      142.47949
2013-10-20      BTC            160.33883  ...       167.07999      152.51350

[20 rows x 5 columns]

In [4]:
len(df)

2787

In [5]:
df.tail()

           Currency  Closing Price (USD)  ...  24h High (USD)  24h Low (USD)
Date                                      ...
2021-05-14      BTC         49764.132082  ...    51448.798576   46294.720180
2021-05-15      BTC         50032.693137  ...    51578.312545   48944.346536
2021-05-16      BTC         47885.625255  ...    50690.802950   47005.102292
2021-05-17      BTC         45604.615754  ...    49670.414174   43868.638969
2021-05-18      BTC         43144.471291  ...    46622.853437   42102.346430

[5 rows x 5 columns]